# Generated by Django 5.2.14 on 2026-05-08 19:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreCompetency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Codes must be lowercase alphanumeric slugs.', regex='^[a-z0-9]+(?:[-_][a-z0-9]+)*$')])),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Codes must be lowercase alphanumeric slugs.', regex='^[a-z0-9]+(?:[-_][a-z0-9]+)*$')])),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PertinentContemporaryIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Codes must be lowercase alphanumeric slugs.', regex='^[a-z0-9]+(?:[-_][a-z0-9]+)*$')])),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecificLearningOutcome',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Specific learning outcome',
                'verbose_name_plural': 'Specific learning outcomes',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumSourceDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_authority', models.SlugField(choices=[('kicd', 'Kenya Institute of Curriculum Development'), ('ministry_of_education', 'Ministry of Education'), ('project_official', 'Project-provided official source')], max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('document_code', models.CharField(max_length=128)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('document_version_label', models.CharField(max_length=128)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Curriculum source document',
                'verbose_name_plural': 'Curriculum source documents',
                'ordering': ['-updated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['source_authority', 'is_active'], name='curr_source_authority_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_authority', 'document_code', 'document_version_label'), name='curriculum_source_document_unique')],
            },
        ),
        migrations.CreateModel(
            name='CurriculumStage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Codes must be lowercase alphanumeric slugs.', regex='^[a-z0-9]+(?:[-_][a-z0-9]+)*$')])),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Curriculum stage',
                'verbose_name_plural': 'Curriculum stages',
                'ordering': ['-updated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['code', 'is_active'], name='curr_stage_code_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurriculumVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(max_length=128)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_versions', to='curriculum.curriculumsourcedocument')),
            ],
            options={
                'verbose_name': 'Curriculum version',
                'verbose_name_plural': 'Curriculum versions',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumLearningArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('official_name', models.CharField(max_length=150)),
                ('official_code', models.SlugField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_learning_areas', to='academics.gradelevel')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_mappings', to='academics.learningarea')),
                ('curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_learning_areas', to='curriculum.curriculumversion')),
            ],
            options={
                'verbose_name': 'Curriculum learning area',
                'verbose_name_plural': 'Curriculum learning areas',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumGradeMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_grade_mappings', to='academics.gradelevel')),
                ('curriculum_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_mappings', to='curriculum.curriculumstage')),
                ('curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_mappings', to='curriculum.curriculumversion')),
            ],
            options={
                'verbose_name': 'Curriculum grade mapping',
                'verbose_name_plural': 'Curriculum grade mappings',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutcomeValueLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome_links', to='curriculum.curriculumvalue')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_links', to='curriculum.specificlearningoutcome')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutcomePCILink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('pci', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome_links', to='curriculum.pertinentcontemporaryissue')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pci_links', to='curriculum.specificlearningoutcome')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutcomeCompetencyLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome_links', to='curriculum.corecompetency')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_links', to='curriculum.specificlearningoutcome')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('curriculum_learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='curriculum.curriculumlearningarea')),
            ],
            options={
                'verbose_name': 'Strand',
                'verbose_name_plural': 'Strands',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubStrand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('suggested_time_allocation', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_strands', to='curriculum.strand')),
            ],
            options={
                'verbose_name': 'Sub-strand',
                'verbose_name_plural': 'Sub-strands',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='specificlearningoutcome',
            name='sub_strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='curriculum.substrand'),
        ),
        migrations.CreateModel(
            name='LearningExperience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('learning_outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_experiences', to='curriculum.specificlearningoutcome')),
                ('sub_strand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_experiences', to='curriculum.substrand')),
            ],
            options={
                'verbose_name': 'Learning experience',
                'verbose_name_plural': 'Learning experiences',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeyInquiryQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sub_strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_inquiry_questions', to='curriculum.substrand')),
            ],
            options={
                'verbose_name': 'Key inquiry question',
                'verbose_name_plural': 'Key inquiry questions',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentRubricFoundation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_code', models.SlugField(max_length=64, validators=[django.core.validators.RegexValidator(message='Codes must be lowercase alphanumeric slugs.', regex='^[a-z0-9]+(?:[-_][a-z0-9]+)*$')])),
                ('level_label', models.CharField(max_length=128)),
                ('descriptor', models.TextField()),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('learning_outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_foundations', to='curriculum.specificlearningoutcome')),
                ('sub_strand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_foundations', to='curriculum.substrand')),
            ],
            options={
                'verbose_name': 'Assessment rubric foundation',
                'verbose_name_plural': 'Assessment rubric foundations',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='curriculumversion',
            index=models.Index(fields=['is_active', 'effective_from'], name='curr_ver_idx'),
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.UniqueConstraint(fields=('source_document', 'version_label'), name='curriculum_version_source_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('source_document',), name='curriculum_one_active_version_per_source'),
        ),
        migrations.AddIndex(
            model_name='curriculumlearningarea',
            index=models.Index(fields=['curriculum_version', 'grade_level', 'is_active'], name='curr_learning_area_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='curriculumlearningarea',
            constraint=models.UniqueConstraint(fields=('curriculum_version', 'grade_level', 'learning_area'), name='curriculum_learning_area_unique'),
        ),
        migrations.AddIndex(
            model_name='curriculumgrademapping',
            index=models.Index(fields=['curriculum_version', 'grade_level'], name='curr_grade_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='curriculumgrademapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('grade_level', 'curriculum_version'), name='curriculum_active_grade_mapping_unique'),
        ),
        migrations.AddConstraint(
            model_name='outcomevaluelink',
            constraint=models.UniqueConstraint(fields=('learning_outcome', 'value'), name='curr_outcome_value_unique'),
        ),
        migrations.AddConstraint(
            model_name='outcomepcilink',
            constraint=models.UniqueConstraint(fields=('learning_outcome', 'pci'), name='curr_outcome_pci_unique'),
        ),
        migrations.AddConstraint(
            model_name='outcomecompetencylink',
            constraint=models.UniqueConstraint(fields=('learning_outcome', 'competency'), name='curr_outcome_competency_unique'),
        ),
        migrations.AddIndex(
            model_name='strand',
            index=models.Index(fields=['curriculum_learning_area', 'sequence_order'], name='curr_strand_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='strand',
            constraint=models.UniqueConstraint(fields=('curriculum_learning_area', 'title'), name='curriculum_strand_title_unique'),
        ),
        migrations.AddConstraint(
            model_name='strand',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('curriculum_learning_area', 'code'), name='curriculum_strand_code_unique'),
        ),
        migrations.AddIndex(
            model_name='substrand',
            index=models.Index(fields=['strand', 'sequence_order'], name='curr_substrand_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='substrand',
            constraint=models.UniqueConstraint(fields=('strand', 'title'), name='curriculum_substrand_title_unique'),
        ),
        migrations.AddConstraint(
            model_name='substrand',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('strand', 'code'), name='curriculum_substrand_code_unique'),
        ),
        migrations.AddIndex(
            model_name='specificlearningoutcome',
            index=models.Index(fields=['sub_strand', 'sequence_order'], name='curr_outcome_order_idx'),
        ),
        migrations.AddIndex(
            model_name='learningexperience',
            index=models.Index(fields=['learning_outcome', 'sequence_order'], name='curr_experience_outcome_idx'),
        ),
        migrations.AddIndex(
            model_name='keyinquiryquestion',
            index=models.Index(fields=['sub_strand', 'sequence_order'], name='curr_inquiry_order_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentrubricfoundation',
            index=models.Index(fields=['learning_outcome', 'sequence_order'], name='curr_rubric_outcome_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrubricfoundation',
            constraint=models.UniqueConstraint(condition=models.Q(('learning_outcome__isnull', False)), fields=('learning_outcome', 'level_code'), name='curr_rubric_outcome_level_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrubricfoundation',
            constraint=models.UniqueConstraint(condition=models.Q(('sub_strand__isnull', False)), fields=('sub_strand', 'level_code'), name='curr_rubric_substrand_level_unique'),
        ),
    ]
