# Generated by Django 5.2.14 on 2026-05-13 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('curriculum', '0002_cct'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumDiff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diff_status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=32)),
                ('summary', models.TextField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('new_curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_curriculum_diffs', to='curriculum.curriculumversion')),
                ('old_curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_curriculum_diffs', to='curriculum.curriculumversion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_curriculum_diffs', to=settings.AUTH_USER_MODEL)),
                ('source_change_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_diffs', to='curriculum.curriculumchangeset')),
            ],
            options={
                'verbose_name': 'Curriculum diff',
                'verbose_name_plural': 'Curriculum diffs',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumDiffItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed'), ('renamed', 'Renamed'), ('moved', 'Moved'), ('updated', 'Updated'), ('retired', 'Retired'), ('reactivated', 'Reactivated'), ('assessment_criteria_changed', 'Assessment criteria changed'), ('effective_date_changed', 'Effective date changed')], max_length=48)),
                ('entity_type', models.CharField(choices=[('curriculum_version', 'Curriculum version'), ('grade_level', 'Grade level'), ('pathway', 'Pathway'), ('learning_area', 'Learning area'), ('strand', 'Strand'), ('sub_strand', 'Sub-strand'), ('outcome', 'Outcome'), ('competency', 'Competency'), ('value', 'Value'), ('pci', 'PCI'), ('rubric_foundation', 'Rubric foundation'), ('assessment_guidance', 'Assessment guidance'), ('teacher_training_notice', 'Teacher training notice'), ('circular', 'Circular')], max_length=64)),
                ('entity_identifier', models.CharField(max_length=255)),
                ('old_value_fingerprint', models.CharField(blank=True, max_length=96)),
                ('new_value_fingerprint', models.CharField(blank=True, max_length=96)),
                ('summary', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('requires_review', models.BooleanField(db_index=True, default=True)),
                ('curriculum_diff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='curriculum.curriculumdiff')),
            ],
            options={
                'verbose_name': 'Curriculum diff item',
                'verbose_name_plural': 'Curriculum diff items',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumImpact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('affected_stage', models.CharField(max_length=128)),
                ('affected_pathway', models.CharField(blank=True, max_length=128)),
                ('impact_category', models.CharField(choices=[('senior_school_curriculum', 'Senior School curriculum'), ('junior_to_senior_transition', 'Junior-to-Senior transition'), ('assessment_criteria', 'Assessment criteria'), ('teacher_readiness', 'Teacher readiness'), ('scheme_review_required', 'Scheme review required'), ('grading_dependency_future', 'Future grading dependency'), ('report_dependency_future', 'Future report dependency'), ('lesson_assistant_dependency_future', 'Future lesson assistant dependency'), ('school_adoption_required', 'School adoption required')], max_length=64)),
                ('impact_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('action_required', models.TextField()),
                ('affected_grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_impacts', to='academics.gradelevel')),
                ('affected_learning_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_impacts', to='curriculum.curriculumlearningarea')),
                ('affected_outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_impacts', to='curriculum.specificlearningoutcome')),
                ('affected_rubric_foundation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_impacts', to='curriculum.assessmentrubricfoundation')),
                ('affected_strand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_impacts', to='curriculum.strand')),
                ('affected_sub_strand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_impacts', to='curriculum.substrand')),
                ('curriculum_diff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='curriculum.curriculumdiff')),
                ('diff_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='curriculum.curriculumdiffitem')),
            ],
            options={
                'verbose_name': 'Curriculum impact',
                'verbose_name_plural': 'Curriculum impacts',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegulatoryNotice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notice_type', models.CharField(choices=[('moe_circular', 'MoE circular'), ('kicd_curriculum_update', 'KICD curriculum update'), ('knec_assessment_guidance', 'KNEC assessment guidance'), ('tsc_teacher_update', 'TSC teacher update'), ('teacher_training_notice', 'Teacher training notice'), ('senior_school_transition_notice', 'Senior School transition notice'), ('pathway_guidance', 'Pathway guidance'), ('implementation_guidance', 'Implementation guidance')], max_length=48)),
                ('title', models.CharField(max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=128)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('review_status', models.CharField(choices=[('pending_review', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending_review', max_length=32)),
                ('notice_status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32)),
                ('affects_senior_school', models.BooleanField(db_index=True, default=False)),
                ('affects_junior_to_senior_transition', models.BooleanField(db_index=True, default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_notices', to='curriculum.curriculumauthority')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_regulatory_notices', to=settings.AUTH_USER_MODEL)),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_notices', to='curriculum.sourceartifact')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_notices', to='curriculum.curriculumsourcedocument')),
            ],
            options={
                'verbose_name': 'Regulatory notice',
                'verbose_name_plural': 'Regulatory notices',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegulatoryImpact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('affected_pathway', models.CharField(blank=True, max_length=128)),
                ('impact_category', models.CharField(choices=[('senior_school_pathway', 'Senior School pathway'), ('senior_school_readiness', 'Senior School readiness'), ('teacher_training', 'Teacher training'), ('assessment_policy', 'Assessment policy'), ('school_infrastructure_readiness', 'School infrastructure readiness'), ('timetable_or_term_guidance', 'Timetable or term guidance'), ('curriculum_implementation', 'Curriculum implementation'), ('junior_to_senior_transition', 'Junior-to-Senior transition')], max_length=64)),
                ('impact_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('action_required', models.TextField()),
                ('affected_grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_impacts', to='academics.gradelevel')),
                ('affected_learning_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_impacts', to='academics.learningarea')),
                ('regulatory_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_impacts', to='curriculum.regulatorynotice')),
            ],
            options={
                'verbose_name': 'Regulatory impact',
                'verbose_name_plural': 'Regulatory impacts',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrincipalNotificationEvidenceCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('curriculum_update', 'Curriculum update'), ('regulatory_notice', 'Regulatory notice'), ('teacher_readiness_update', 'Teacher readiness update'), ('assessment_guidance_update', 'Assessment guidance update'), ('junior_to_senior_transition_update', 'Junior-to-Senior transition update'), ('school_activation_required', 'School activation required')], max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('evidence_summary', models.TextField()),
                ('required_action', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready for review'), ('issued', 'Issued'), ('acknowledged', 'Acknowledged'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_principal_notification_cards', to=settings.AUTH_USER_MODEL)),
                ('curriculum_diff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='principal_notification_cards', to='curriculum.curriculumdiff')),
                ('curriculum_impact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='principal_notification_cards', to='curriculum.curriculumimpact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_notification_cards', to='tenant.school')),
                ('regulatory_notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='principal_notification_cards', to='curriculum.regulatorynotice')),
            ],
            options={
                'verbose_name': 'Principal notification evidence card',
                'verbose_name_plural': 'Principal notification evidence cards',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolUpdateAcknowledgement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField()),
                ('acknowledgement_status', models.CharField(choices=[('acknowledged', 'Acknowledged'), ('needs_internal_review', 'Needs internal review'), ('deferred', 'Deferred'), ('rejected_for_school_context', 'Rejected for school context')], max_length=48)),
                ('principal_notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_update_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('notification_evidence_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='curriculum.principalnotificationevidencecard')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_update_acknowledgements', to='tenant.school')),
            ],
            options={
                'verbose_name': 'School update acknowledgement',
                'verbose_name_plural': 'School update acknowledgements',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherReadinessRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('affected_pathway', models.CharField(blank=True, max_length=128)),
                ('requirement_type', models.CharField(choices=[('training_required', 'Training required'), ('retooling_required', 'Retooling required'), ('assessment_training_required', 'Assessment training required'), ('pathway_readiness_required', 'Pathway readiness required'), ('implementation_briefing_required', 'Implementation briefing required')], max_length=48)),
                ('summary', models.TextField()),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('affected_grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_readiness_requirements', to='academics.gradelevel')),
                ('affected_learning_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_readiness_requirements', to='academics.learningarea')),
                ('regulatory_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_readiness_requirements', to='curriculum.regulatorynotice')),
            ],
            options={
                'verbose_name': 'Teacher readiness requirement',
                'verbose_name_plural': 'Teacher readiness requirements',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='curriculumdiff',
            index=models.Index(fields=['diff_status', 'created_at'], name='curr_diff_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='curriculumdiff',
            constraint=models.UniqueConstraint(fields=('old_curriculum_version', 'new_curriculum_version'), name='curriculum_diff_version_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='curriculumdiff',
            constraint=models.CheckConstraint(condition=models.Q(('old_curriculum_version', models.F('new_curriculum_version')), _negated=True), name='curriculum_diff_versions_differ'),
        ),
        migrations.AddIndex(
            model_name='curriculumdiffitem',
            index=models.Index(fields=['curriculum_diff', 'requires_review'], name='curr_diff_item_review_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumdiffitem',
            index=models.Index(fields=['entity_type', 'change_type'], name='curr_diff_item_type_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumimpact',
            index=models.Index(fields=['impact_category', 'impact_severity'], name='curr_impact_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorynotice',
            index=models.Index(fields=['review_status', 'notice_status'], name='curr_notice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorynotice',
            index=models.Index(fields=['affects_senior_school'], name='curr_notice_senior_idx'),
        ),
        migrations.AddConstraint(
            model_name='regulatorynotice',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_number', ''), _negated=True), fields=('authority', 'reference_number'), name='curr_reg_notice_reference_unique'),
        ),
        migrations.AddIndex(
            model_name='regulatoryimpact',
            index=models.Index(fields=['impact_category', 'impact_severity'], name='curr_reg_impact_idx'),
        ),
        migrations.AddIndex(
            model_name='principalnotificationevidencecard',
            index=models.Index(fields=['tenant', 'status'], name='curr_card_tenant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='principalnotificationevidencecard',
            constraint=models.UniqueConstraint(fields=('tenant', 'regulatory_notice', 'notification_type'), name='curr_notice_card_unique_per_school'),
        ),
        migrations.AddIndex(
            model_name='schoolupdateacknowledgement',
            index=models.Index(fields=['tenant', 'acknowledgement_status'], name='curr_ack_tenant_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolupdateacknowledgement',
            constraint=models.UniqueConstraint(fields=('tenant', 'notification_evidence_card'), name='curr_school_ack_unique'),
        ),
        migrations.AddIndex(
            model_name='teacherreadinessrequirement',
            index=models.Index(fields=['requirement_type', 'is_active'], name='curr_teacher_req_idx'),
        ),
    ]
