# Generated by Django 5.2.14 on 2026-05-17 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_phase4c_regulatory'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumNoticeBatchRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notice_type', models.CharField(choices=[('principal_evidence', 'Principal evidence'), ('teacher_readiness', 'Teacher readiness'), ('adoption', 'Adoption'), ('withdrawal', 'Withdrawal')], max_length=32)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='planned', max_length=32)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_curriculum_notice_batches', to=settings.AUTH_USER_MODEL)),
                ('curriculum_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notice_batch_runs', to='curriculum.curriculumversion')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_notice_batches', to='tenant.school')),
            ],
            options={
                'verbose_name': 'Curriculum notice batch run',
                'verbose_name_plural': 'Curriculum notice batch runs',
                'ordering': ['-updated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'notice_type', 'created_at'], name='curr_notice_batch_idx'), models.Index(fields=['tenant', 'status'], name='curr_notice_tenant_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurriculumRollbackPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('approved', 'Approved'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=32)),
                ('reason', models.TextField()),
                ('planned_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('affected_assessment_count', models.PositiveIntegerField(default=0)),
                ('planned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_curriculum_rollbacks', to=settings.AUTH_USER_MODEL)),
                ('target_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rollback_plans_as_target', to='curriculum.curriculumversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_rollback_plans', to='tenant.school')),
                ('withdrawn_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rollback_plans_as_withdrawn', to='curriculum.curriculumversion')),
            ],
            options={
                'verbose_name': 'Curriculum rollback plan',
                'verbose_name_plural': 'Curriculum rollback plans',
                'ordering': ['-updated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'status', 'planned_at'], name='curr_rollback_tenant_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurriculumVersionWithdrawal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=32)),
                ('reason', models.TextField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='curriculum.curriculumversion')),
                ('replacement_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_for_withdrawals', to='curriculum.curriculumversion')),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawn_curriculum_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curriculum version withdrawal',
                'verbose_name_plural': 'Curriculum version withdrawals',
                'ordering': ['-updated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['curriculum_version', 'status'], name='curr_withdraw_version_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchoolCurriculumAdoption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn'), ('rolled_back', 'Rolled back')], db_index=True, default='scheduled', max_length=32)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('adopted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('adopted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_curriculum_adoptions', to=settings.AUTH_USER_MODEL)),
                ('curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_adoptions', to='curriculum.curriculumversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_adoptions', to='tenant.school')),
            ],
            options={
                'verbose_name': 'School curriculum adoption',
                'verbose_name_plural': 'School curriculum adoptions',
                'ordering': ['-updated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'status', 'effective_from'], name='curr_adopt_tenant_status_idx'), models.Index(fields=['curriculum_version', 'status'], name='curr_adopt_version_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['scheduled', 'active'])), fields=('tenant', 'curriculum_version'), name='curr_adopt_active_unique')],
            },
        ),
    ]
