# Generated by Django 5.2.14 on 2026-05-17 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_cct_fortification_control_plane'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumEvidenceSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitter_role', models.CharField(max_length=64)),
                ('evidence_type', models.CharField(choices=[('curriculum_update', 'Curriculum update'), ('rollback', 'Rollback'), ('withdrawal', 'Withdrawal')], default='curriculum_update', max_length=32)),
                ('status', models.CharField(choices=[('received', 'Received'), ('quarantined', 'Quarantined'), ('duplicate_attached', 'Duplicate attached'), ('under_verification', 'Under verification'), ('verification_reported', 'Verification reported'), ('escalated', 'Escalated'), ('rejected', 'Rejected'), ('governance_ready', 'Governance ready')], db_index=True, default='quarantined', max_length=32)),
                ('storage_reference', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveIntegerField()),
                ('file_checksum', models.CharField(max_length=96)),
                ('evidence_fingerprint', models.CharField(db_index=True, max_length=96)),
                ('duplicate_cluster_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('claimed_authority', models.CharField(blank=True, max_length=128)),
                ('claimed_source_reference', models.CharField(blank=True, max_length=255)),
                ('claimed_source_url', models.URLField(blank=True, max_length=500)),
                ('claimed_reference_number', models.CharField(blank=True, max_length=128)),
                ('claimed_publication_number', models.CharField(blank=True, max_length=128)),
                ('claimed_publication_date', models.DateField(blank=True, null=True)),
                ('claimed_effective_date', models.DateField(blank=True, null=True)),
                ('claimed_scope', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_submissions', to='curriculum.curriculumevidencesubmission')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_curriculum_evidence', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_evidence_submissions', to='tenant.school')),
            ],
            options={
                'verbose_name': 'Curriculum evidence submission',
                'verbose_name_plural': 'Curriculum evidence submissions',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumVerificationReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_id', models.UUIDField(db_index=True)),
                ('fingerprint', models.CharField(max_length=96)),
                ('source_classification', models.CharField(default='school_evidence', max_length=64)),
                ('claimed_authority', models.CharField(blank=True, max_length=128)),
                ('claimed_source_reference', models.CharField(blank=True, max_length=255)),
                ('reference_number_detected', models.BooleanField(default=False)),
                ('reference_number_value', models.CharField(blank=True, max_length=128)),
                ('publication_number_detected', models.BooleanField(default=False)),
                ('publication_number_value', models.CharField(blank=True, max_length=128)),
                ('publication_date_detected', models.BooleanField(default=False)),
                ('effective_date_detected', models.BooleanField(default=False)),
                ('stamp_signal', models.BooleanField(default=False)),
                ('signature_signal', models.BooleanField(default=False)),
                ('template_signal', models.BooleanField(default=False)),
                ('duplicate_signal_count', models.PositiveIntegerField(default=0)),
                ('official_source_match_status', models.CharField(choices=[('unknown', 'Unknown'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('awaiting_confirmation', 'Awaiting confirmation')], default='unknown', max_length=32)),
                ('scope_guess', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('rejected', 'Rejected'), ('needs_governance_review', 'Needs governance review')], default='low', max_length=32)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('missing_evidence', models.JSONField(blank=True, default=list)),
                ('recommended_next_action', models.CharField(choices=[('keep_quarantined', 'Keep quarantined'), ('request_more_evidence', 'Request more evidence'), ('await_official_confirmation', 'Await official confirmation'), ('escalate_to_governance', 'Escalate to governance'), ('ready_for_governance_review', 'Ready for governance review'), ('reject', 'Reject')], default='keep_quarantined', max_length=48)),
                ('sla_due_at', models.DateTimeField(db_index=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('needs_more_evidence', 'Needs more evidence'), ('awaiting_official_confirmation', 'Awaiting official confirmation'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=48)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_curriculum_verification_reports', to=settings.AUTH_USER_MODEL)),
                ('evidence_submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verification_report', to='curriculum.curriculumevidencesubmission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_verification_reports', to='tenant.school')),
            ],
            options={
                'verbose_name': 'Curriculum verification report',
                'verbose_name_plural': 'Curriculum verification reports',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumRollbackCandidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('suspected', 'Suspected'), ('quarantined', 'Quarantined'), ('under_review', 'Under review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('rollback_planned', 'Rollback planned'), ('withdrawn', 'Withdrawn')], db_index=True, default='quarantined', max_length=32)),
                ('reason', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_curriculum_rollback_candidates', to=settings.AUTH_USER_MODEL)),
                ('evidence_submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rollback_candidates', to='curriculum.curriculumevidencesubmission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_rollback_candidates', to='tenant.school')),
                ('verification_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rollback_candidates', to='curriculum.curriculumverificationreport')),
            ],
            options={
                'verbose_name': 'Curriculum rollback candidate',
                'verbose_name_plural': 'Curriculum rollback candidates',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumGovernanceDecision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved_for_publication', 'Approved for publication'), ('rejected', 'Rejected'), ('requires_more_evidence', 'Requires more evidence'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=48)),
                ('reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_governance_decisions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_governance_decisions', to='tenant.school')),
                ('verification_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_decisions', to='curriculum.curriculumverificationreport')),
            ],
            options={
                'verbose_name': 'Curriculum governance decision',
                'verbose_name_plural': 'Curriculum governance decisions',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumAppImpactPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_domain', models.CharField(db_index=True, max_length=64)),
                ('impact_type', models.CharField(max_length=64)),
                ('affected_scope', models.JSONField(blank=True, default=dict)),
                ('required_action', models.TextField()),
                ('safe_behavior', models.TextField()),
                ('historical_protection_rule', models.TextField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('review_required', 'Review required'), ('approved', 'Approved'), ('paused', 'Paused')], db_index=True, default='planned', max_length=32)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_app_impact_plans', to='tenant.school')),
                ('verification_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_impact_plans', to='curriculum.curriculumverificationreport')),
            ],
            options={
                'verbose_name': 'Curriculum app impact plan',
                'verbose_name_plural': 'Curriculum app impact plans',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='curriculumevidencesubmission',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='curr_evid_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumevidencesubmission',
            index=models.Index(fields=['evidence_fingerprint', 'status'], name='curr_evid_fingerprint_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumevidencesubmission',
            index=models.Index(fields=['duplicate_cluster_id', 'created_at'], name='curr_evid_cluster_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumverificationreport',
            index=models.Index(fields=['tenant', 'review_status', 'sla_due_at'], name='curr_verify_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumverificationreport',
            index=models.Index(fields=['candidate_id', 'confidence_level'], name='curr_verify_candidate_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumrollbackcandidate',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='curr_rb_candidate_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumgovernancedecision',
            index=models.Index(fields=['tenant', 'decision', 'reviewed_at'], name='curr_gov_tenant_decision_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumappimpactplan',
            index=models.Index(fields=['tenant', 'app_domain', 'status'], name='curr_app_impact_tenant_idx'),
        ),
    ]
