# Generated by Django 5.2.14 on 2026-05-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_cct_fullproofing_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumevidencesubmission',
            name='content_verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('unsupported', 'Unsupported')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='curriculumevidencesubmission',
            name='malware_scan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('suspicious', 'Suspicious'), ('infected', 'Infected'), ('unavailable', 'Unavailable')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='curriculumevidencesubmission',
            name='storage_backend',
            field=models.CharField(default='private_internal', max_length=64),
        ),
    ]
