# Generated by Django 5.2.14 on 2026-05-14 10:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('curriculum', '0003_phase4c_regulatory'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('practical', 'Practical'), ('exam', 'Exam'), ('project', 'Project')], default='exam', max_length=32)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('locked', 'Locked'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.academicyear')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('curriculum_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='curriculum.curriculumversion')),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.gradelevel')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.learningarea')),
                ('rubric_foundation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='curriculum.assessmentrubricfoundation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='tenant.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.term')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('normalized_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('rubric_level', models.CharField(blank=True, max_length=32)),
                ('remarks', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_records', to='grading.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_records', to='academics.student')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_grade_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='tenant.school')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeCorrectionRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('old_state_hash', models.CharField(max_length=96)),
                ('proposed_raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('proposed_remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=32)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_correction_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_grade_corrections', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_correction_requests', to='tenant.school')),
                ('grade_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='grading.graderecord')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeSubmissionBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=180)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('compiled', 'Compiled'), ('failed', 'Failed'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('compiled_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_batches', to='grading.assessment')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_batches', to='academics.cohort')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_batches', to='academics.learningarea')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_submission_batches', to=settings.AUTH_USER_MODEL)),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_submission_batches', to='academics.teacherassignment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_batches', to='tenant.school')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='graderecord',
            name='submission_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_records', to='grading.gradesubmissionbatch'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['tenant', 'status'], name='grading_assess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['tenant', 'cohort', 'learning_area'], name='grading_assess_context_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='grading_assessment_max_score_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__lte', 100)), name='grading_assessment_weight_bounded'),
        ),
        migrations.AddIndex(
            model_name='gradecorrectionrequest',
            index=models.Index(fields=['tenant', 'status'], name='grading_corr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='gradecorrectionrequest',
            index=models.Index(fields=['grade_record', 'status'], name='grading_corr_record_idx'),
        ),
        migrations.AddIndex(
            model_name='gradesubmissionbatch',
            index=models.Index(fields=['tenant', 'assessment'], name='grading_batch_assess_idx'),
        ),
        migrations.AddIndex(
            model_name='gradesubmissionbatch',
            index=models.Index(fields=['tenant', 'teacher'], name='grading_batch_teacher_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradesubmissionbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['submitted', 'validated', 'compiled'])), fields=('tenant', 'assessment', 'teacher', 'teacher_assignment'), name='grading_active_batch_unique'),
        ),
        migrations.AddConstraint(
            model_name='gradesubmissionbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='grading_batch_idempotency_unique'),
        ),
        migrations.AddIndex(
            model_name='graderecord',
            index=models.Index(fields=['tenant', 'assessment'], name='grading_record_assess_idx'),
        ),
        migrations.AddIndex(
            model_name='graderecord',
            index=models.Index(fields=['tenant', 'student'], name='grading_record_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='graderecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'assessment', 'student'), name='grading_record_assessment_student_unique'),
        ),
        migrations.AddConstraint(
            model_name='graderecord',
            constraint=models.CheckConstraint(condition=models.Q(('raw_score__gte', 0)), name='grading_record_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='graderecord',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='grading_record_version_positive'),
        ),
    ]
