# Generated by Django 5.2.14 on 2026-05-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='curriculum_binding_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
