# Generated by Django 5.2.14 on 2026-05-14 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('curriculum', '0003_phase4c_regulatory'),
        ('grading', '0002_assessment_curriculum_binding_locked_at'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graderecord',
            name='component_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gradesubmissionbatch',
            name='confirmation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradesubmissionbatch',
            name='confirmation_method',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='gradesubmissionbatch',
            name='confirmation_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='gradesubmissionbatch',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.CreateModel(
            name='GradeDraftBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=180)),
                ('payload_hash', models.CharField(blank=True, max_length=96)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('discarded', 'Discarded')], db_index=True, default='draft', max_length=32)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_batches', to='grading.assessment')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_draft_batches', to='academics.cohort')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_draft_batches', to='academics.learningarea')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_draft_batches', to=settings.AUTH_USER_MODEL)),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_draft_batches', to='academics.teacherassignment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_draft_batches', to='tenant.school')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeDraftRow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('component_scores', models.JSONField(blank=True, default=dict)),
                ('remarks', models.TextField(blank=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('draft_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='grading.gradedraftbatch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_draft_rows', to='academics.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_draft_rows', to='tenant.school')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='grading.assessment')),
                ('rubric_foundation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_components', to='curriculum.assessmentrubricfoundation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_components', to='tenant.school')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'assessment', 'order'], name='grading_component_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'assessment', 'name'), name='grading_component_name_unique'), models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='grading_component_max_score_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='gradedraftbatch',
            index=models.Index(fields=['tenant', 'assessment', 'teacher', 'status'], name='grading_draft_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradedraftbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('tenant', 'assessment', 'teacher'), name='grading_one_active_draft_unique'),
        ),
        migrations.AddConstraint(
            model_name='gradedraftbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='grading_draft_idempotency_unique'),
        ),
        migrations.AddIndex(
            model_name='gradedraftrow',
            index=models.Index(fields=['tenant', 'draft_batch'], name='grading_draft_row_batch_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradedraftrow',
            constraint=models.UniqueConstraint(fields=('draft_batch', 'student'), name='grading_draft_row_student_unique'),
        ),
        migrations.AddConstraint(
            model_name='gradedraftrow',
            constraint=models.CheckConstraint(condition=models.Q(('raw_score__gte', 0), ('raw_score__isnull', True), _connector='OR'), name='grading_draft_row_score_non_negative'),
        ),
    ]
