# Generated by Django 5.2.14 on 2026-05-16 13:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('curriculum', '0003_phase4c_regulatory'),
        ('grading', '0003_graderecord_component_scores_and_more'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompilationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('partial', 'Partial'), ('failed', 'Failed'), ('stale', 'Stale'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=32)),
                ('expected_learner_count', models.PositiveIntegerField(default=0)),
                ('submitted_learner_count', models.PositiveIntegerField(default=0)),
                ('missing_learner_count', models.PositiveIntegerField(default=0)),
                ('source_batch_ids', models.JSONField(blank=True, default=list)),
                ('error_summary', models.CharField(blank=True, max_length=255)),
                ('compiled_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compilation_runs', to='grading.assessment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_compilation_runs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compilation_runs', to='tenant.school')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompiledAssessmentSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('compiled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compiled_assessment_snapshots', to='grading.assessment')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.cohort')),
                ('compilation_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_snapshot', to='grading.compilationrun')),
                ('curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.curriculumversion')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.learningarea')),
                ('rubric_foundation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.assessmentrubricfoundation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compiled_assessment_snapshots', to='tenant.school')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompiledCohortSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_learner_count', models.PositiveIntegerField(default=0)),
                ('submitted_learner_count', models.PositiveIntegerField(default=0)),
                ('missing_learner_count', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('component_summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('compiled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grading.assessment')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.cohort')),
                ('compilation_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_summary', to='grading.compilationrun')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.learningarea')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compiled_cohort_summaries', to='tenant.school')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompiledLearnerSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('score_summary', models.JSONField(blank=True, default=dict)),
                ('component_summary', models.JSONField(blank=True, default=dict)),
                ('missing_marks', models.JSONField(blank=True, default=list)),
                ('cbe_band_status', models.CharField(blank=True, max_length=64)),
                ('source_batch_ids', models.JSONField(blank=True, default=list)),
                ('compiled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grading.assessment')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.cohort')),
                ('compilation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_snapshots', to='grading.compilationrun')),
                ('curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.curriculumversion')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.learningarea')),
                ('rubric_foundation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.assessmentrubricfoundation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compiled_learner_snapshots', to='tenant.school')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='compilationrun',
            index=models.Index(fields=['tenant', 'assessment', 'status'], name='grading_compile_run_idx'),
        ),
        migrations.AddIndex(
            model_name='compiledassessmentsnapshot',
            index=models.Index(fields=['tenant', 'assessment', 'status'], name='grading_assess_snap_idx'),
        ),
        migrations.AddIndex(
            model_name='compiledcohortsummary',
            index=models.Index(fields=['tenant', 'cohort', 'learning_area', 'status'], name='grading_cohort_summary_idx'),
        ),
        migrations.AddIndex(
            model_name='compiledlearnersnapshot',
            index=models.Index(fields=['tenant', 'assessment', 'student'], name='grading_learn_snap_idx'),
        ),
        migrations.AddIndex(
            model_name='compiledlearnersnapshot',
            index=models.Index(fields=['tenant', 'cohort', 'learning_area'], name='grading_learn_snap_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='compiledlearnersnapshot',
            constraint=models.UniqueConstraint(fields=('tenant', 'assessment', 'student', 'compilation_run'), name='grading_compiled_learner_unique'),
        ),
    ]
