# Generated by Django 5.2.14 on 2026-05-19 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_phase6c_compilation_snapshots'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='school_grading_schema_version',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='gradecorrectionrequest',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradecorrectionrequest',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_grade_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradecorrectionrequest',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradecorrectionrequest',
            name='escalated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalated_grade_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradecorrectionrequest',
            name='escalation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gradecorrectionrequest',
            name='proposed_component_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gradecorrectionrequest',
            name='reason_code',
            field=models.CharField(default='teacher_request', max_length=64),
        ),
        migrations.AddField(
            model_name='gradecorrectionrequest',
            name='review_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='internal_band_descriptor',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='internal_band_label',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='school_grading_schema_version',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('practical', 'Practical'), ('exam', 'Exam'), ('project', 'Project'), ('cat', 'CAT'), ('internal_exam', 'Internal exam'), ('mock_exam', 'Mock exam'), ('trial_exam', 'Trial exam'), ('departmental_test', 'Departmental test'), ('practical_component', 'Practical component'), ('cbe_rubric_assessment', 'CBE rubric assessment')], default='exam', max_length=32),
        ),
        migrations.AlterField(
            model_name='gradecorrectionrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('submitted', 'Submitted'), ('under_hod_review', 'Under HOD review'), ('approved', 'Approved'), ('approved_by_hod', 'Approved by HOD'), ('rejected', 'Rejected'), ('rejected_by_hod', 'Rejected by HOD'), ('escalation_requested', 'Escalation requested'), ('under_academic_head_review', 'Under academic head review'), ('approved_by_academic_head', 'Approved by academic head'), ('rejected_by_academic_head', 'Rejected by academic head'), ('applied', 'Applied'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='requested', max_length=32),
        ),
        migrations.CreateModel(
            name='SchoolGradingSchema',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('practical', 'Practical'), ('exam', 'Exam'), ('project', 'Project'), ('cat', 'CAT'), ('internal_exam', 'Internal exam'), ('mock_exam', 'Mock exam'), ('trial_exam', 'Trial exam'), ('departmental_test', 'Departmental test'), ('practical_component', 'Practical component'), ('cbe_rubric_assessment', 'CBE rubric assessment')], max_length=32)),
                ('version_label', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('retired', 'Retired'), ('locked', 'Locked')], db_index=True, default='draft', max_length=32)),
                ('requires_full_coverage', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_school_grading_schemas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_school_grading_schemas', to=settings.AUTH_USER_MODEL)),
                ('deprecated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deprecated_school_grading_schemas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_grading_schemas', to='tenant.school')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolGradingBand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=32)),
                ('descriptor', models.CharField(blank=True, max_length=160)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_grading_bands', to='tenant.school')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='grading.schoolgradingschema')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='school_grading_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='grading.schoolgradingschema'),
        ),
        migrations.CreateModel(
            name='GradeCorrectionAuditRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('requested', 'Requested'), ('reviewed', 'Reviewed'), ('escalated', 'Escalated'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], db_index=True, max_length=32)),
                ('status_from', models.CharField(blank=True, max_length=32)),
                ('status_to', models.CharField(max_length=32)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('reason_summary', models.CharField(blank=True, max_length=180)),
                ('state_before_hash', models.CharField(blank=True, max_length=96)),
                ('state_after_hash', models.CharField(blank=True, max_length=96)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_correction_audit_records', to=settings.AUTH_USER_MODEL)),
                ('correction_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_records', to='grading.gradecorrectionrequest')),
                ('grade_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_audit_records', to='grading.graderecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_correction_audit_records', to='tenant.school')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'correction_request', 'created_at'], name='grading_corr_audit_req_idx'), models.Index(fields=['tenant', 'grade_record', 'created_at'], name='grading_corr_audit_record_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='schoolgradingschema',
            index=models.Index(fields=['tenant', 'assessment_type', 'status'], name='grading_schema_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolgradingschema',
            constraint=models.UniqueConstraint(fields=('tenant', 'assessment_type', 'version_label'), name='grading_schema_type_version_unique'),
        ),
        migrations.AddIndex(
            model_name='schoolgradingband',
            index=models.Index(fields=['tenant', 'schema', 'order'], name='grading_schema_band_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolgradingband',
            constraint=models.UniqueConstraint(fields=('tenant', 'schema', 'label'), name='grading_schema_band_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='schoolgradingband',
            constraint=models.CheckConstraint(condition=models.Q(('min_percentage__gte', 0), ('max_percentage__lte', 100)), name='grading_schema_band_pct_bounds'),
        ),
        migrations.AddConstraint(
            model_name='schoolgradingband',
            constraint=models.CheckConstraint(condition=models.Q(('min_percentage__lte', models.F('max_percentage'))), name='grading_schema_band_pct_order'),
        ),
    ]
