# Generated by Django 5.2.14 on 2026-05-21 08:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('curriculum', '0006_cct_production_readiness_upload_status'),
        ('grading', '0005_assessment_school_grading_schema_version_and_more'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshotRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('partial', 'Partial'), ('blocked', 'Blocked'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('eligibility_summary', models.JSONField(blank=True, default=dict)),
                ('source_compilation_run_ids', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_snapshot_runs', to='academics.academicyear')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_report_snapshot_runs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshot_runs', to='tenant.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_snapshot_runs', to='academics.term')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportEligibilityRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('eligible', 'Eligible'), ('blocked', 'Blocked')], db_index=True, max_length=32)),
                ('readiness_status', models.CharField(blank=True, max_length=64)),
                ('blocker_codes', models.JSONField(blank=True, default=list)),
                ('source_readiness', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_eligibility_records', to='grading.assessment')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.cohort')),
                ('compilation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_eligibility_records', to='grading.compilationrun')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.learningarea')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_eligibility_records', to='tenant.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
                ('snapshot_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_records', to='grading.reportsnapshotrun')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearnerReportSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('stale', 'Stale')], db_index=True, default='active', max_length=32)),
                ('subject_count', models.PositiveIntegerField(default=0)),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('average_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('source_compilation_run_ids', models.JSONField(blank=True, default=list)),
                ('readiness_status', models.CharField(blank=True, max_length=64)),
                ('correction_audit_state', models.JSONField(blank=True, default=dict)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('schema_versions', models.JSONField(blank=True, default=dict)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.cohort')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_snapshots', to='academics.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_report_snapshots', to='tenant.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
                ('snapshot_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_snapshots', to='grading.reportsnapshotrun')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicAggregate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('school', 'School'), ('cohort', 'Cohort'), ('stream', 'Stream'), ('subject', 'Subject'), ('department', 'Department')], db_index=True, max_length=32)),
                ('stream_label', models.CharField(blank=True, max_length=64)),
                ('department_key', models.CharField(blank=True, max_length=96)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('min_group_size_met', models.BooleanField(default=True)),
                ('status', models.CharField(db_index=True, default='computed', max_length=32)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.cohort')),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.gradelevel')),
                ('learning_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.learningarea')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_aggregates', to='tenant.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
                ('snapshot_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_aggregates', to='grading.reportsnapshotrun')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportSubjectLineSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_grading_schema_version', models.CharField(blank=True, max_length=48)),
                ('score_summary', models.JSONField(blank=True, default=dict)),
                ('component_summary', models.JSONField(blank=True, default=dict)),
                ('cbe_band_status', models.CharField(blank=True, max_length=64)),
                ('internal_band_label', models.CharField(blank=True, max_length=32)),
                ('internal_band_descriptor', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grading.assessment')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.cohort')),
                ('compilation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grading.compilationrun')),
                ('compiled_learner_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_subject_lines', to='grading.compiledlearnersnapshot')),
                ('curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.curriculumversion')),
                ('learner_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_lines', to='grading.learnerreportsnapshot')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.learningarea')),
                ('rubric_foundation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.assessmentrubricfoundation')),
                ('snapshot_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_line_snapshots', to='grading.reportsnapshotrun')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_subject_line_snapshots', to='tenant.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='reportsnapshotrun',
            index=models.Index(fields=['tenant', 'academic_year', 'term', 'status'], name='grading_report_run_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='reporteligibilityrecord',
            index=models.Index(fields=['tenant', 'snapshot_run', 'status'], name='grading_report_elig_run_idx'),
        ),
        migrations.AddIndex(
            model_name='reporteligibilityrecord',
            index=models.Index(fields=['tenant', 'assessment', 'status'], name='grading_report_elig_assess_idx'),
        ),
        migrations.AddIndex(
            model_name='learnerreportsnapshot',
            index=models.Index(fields=['tenant', 'snapshot_run', 'cohort', 'status'], name='grading_lrn_report_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='learnerreportsnapshot',
            index=models.Index(fields=['tenant', 'student', 'academic_year', 'term'], name='grading_lrn_report_stud_idx'),
        ),
        migrations.AddConstraint(
            model_name='learnerreportsnapshot',
            constraint=models.UniqueConstraint(fields=('tenant', 'snapshot_run', 'student'), name='grading_learner_report_unique'),
        ),
        migrations.AddIndex(
            model_name='academicaggregate',
            index=models.Index(fields=['tenant', 'snapshot_run', 'scope_type', 'status'], name='grading_acad_agg_run_idx'),
        ),
        migrations.AddIndex(
            model_name='academicaggregate',
            index=models.Index(fields=['tenant', 'academic_year', 'term', 'scope_type'], name='grading_acad_agg_period_idx'),
        ),
        migrations.AddIndex(
            model_name='academicaggregate',
            index=models.Index(fields=['tenant', 'cohort', 'learning_area'], name='grading_acad_agg_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsubjectlinesnapshot',
            index=models.Index(fields=['tenant', 'snapshot_run', 'cohort', 'learning_area'], name='grading_rpt_subj_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsubjectlinesnapshot',
            index=models.Index(fields=['tenant', 'learning_area', 'status'], name='grading_rpt_subj_area_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportsubjectlinesnapshot',
            constraint=models.UniqueConstraint(fields=('tenant', 'snapshot_run', 'assessment', 'student'), name='grading_report_subject_unique'),
        ),
    ]
