# Generated by Django 5.2.14 on 2026-05-13 06:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=128)),
                ('event_version', models.PositiveIntegerField(default=1)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('source_module', models.CharField(max_length=64)),
                ('partition_key', models.CharField(max_length=128)),
                ('priority', models.CharField(db_index=True, default='normal', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('locked', 'Locked'), ('dispatched', 'Dispatched'), ('failed_retryable', 'Failed retryable'), ('dead_lettered', 'Dead lettered'), ('discarded_invalid', 'Discarded invalid')], db_index=True, default='pending', max_length=32)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=128)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_outbox_records', to='tenant.school')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventDispatchAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('dispatcher_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed_retryable', 'Failed retryable'), ('dead_lettered', 'Dead lettered')], max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_outbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_attempts', to='events.eventoutbox')),
            ],
        ),
        migrations.CreateModel(
            name='EventConsumerState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('consumer_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('started', 'Started'), ('processed', 'Processed'), ('failed', 'Failed')], max_length=32)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_consumer_states', to='tenant.school')),
                ('event_outbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_states', to='events.eventoutbox')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeadLetterEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=128)),
                ('event_version', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('sanitized_error', models.CharField(blank=True, max_length=255)),
                ('failed_after_attempts', models.PositiveIntegerField()),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dead_letter_events', to='tenant.school')),
                ('event_outbox', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dead_letter', to='events.eventoutbox')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=128)),
                ('resource_type', models.CharField(max_length=128)),
                ('resource_id', models.CharField(max_length=128)),
                ('old_state_hash', models.CharField(blank=True, max_length=96)),
                ('new_state_hash', models.CharField(blank=True, max_length=96)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='tenant.school')),
                ('event_outbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='events.eventoutbox')),
            ],
        ),
        migrations.CreateModel(
            name='EventTypeRegistry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=128)),
                ('event_version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('source_module', models.CharField(max_length=64)),
                ('allowed_producers', models.JSONField(default=list)),
                ('allowed_consumers', models.JSONField(default=list)),
                ('requires_tenant', models.BooleanField(default=True)),
                ('pii_policy', models.CharField(choices=[('no_pii', 'No PII'), ('references_only', 'References only')], default='references_only', max_length=32)),
                ('payload_schema', models.JSONField(default=dict)),
                ('priority', models.CharField(default='normal', max_length=16)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['event_type', 'event_version'], name='events_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'event_version'), name='events_type_version_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='eventoutbox',
            index=models.Index(fields=['status', 'available_at', 'priority', 'occurred_at'], name='events_outbox_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoutbox',
            index=models.Index(fields=['tenant', 'status'], name='events_outbox_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdispatchattempt',
            index=models.Index(fields=['event_outbox', 'attempt_number'], name='events_attempt_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventconsumerstate',
            constraint=models.UniqueConstraint(fields=('event_id', 'consumer_name'), name='events_consumer_once_unique'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['tenant', 'occurred_at'], name='events_audit_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['resource_type', 'resource_id'], name='events_audit_resource_idx'),
        ),
    ]
