# Generated by Django 5.2.14 on 2026-05-08 15:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='tenant.school')),
            ],
            options={
                'verbose_name': 'Academic year',
                'verbose_name_plural': 'Academic years',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Codes must be lowercase alphanumeric slugs.', regex='^[a-z0-9]+(?:[-_][a-z0-9]+)*$')])),
                ('name', models.CharField(max_length=128)),
                ('stage', models.SlugField(choices=[('pre_primary', 'Pre-primary'), ('primary', 'Primary'), ('junior_school', 'Junior school'), ('senior_school', 'Senior school')], max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Grade level',
                'verbose_name_plural': 'Grade levels',
                'ordering': ['-updated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['stage', 'is_active'], name='acad_grade_stage_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stream_label', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='academics.academicyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='tenant.school')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='academics.gradelevel')),
            ],
            options={
                'verbose_name': 'Cohort',
                'verbose_name_plural': 'Cohorts',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, validators=[django.core.validators.RegexValidator(message='Codes must be lowercase alphanumeric slugs.', regex='^[a-z0-9]+(?:[-_][a-z0-9]+)*$')])),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_areas', to='academics.gradelevel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_areas', to='tenant.school')),
            ],
            options={
                'verbose_name': 'Learning area',
                'verbose_name_plural': 'Learning areas',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
            ],
            options={
                'verbose_name': 'Subject compatibility view',
                'verbose_name_plural': 'Subject compatibility views',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academics.learningarea',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Admission numbers must be uppercase alphanumeric codes.', regex='^[A-Z0-9-]{3,32}$')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='tenant.school')),
            ],
            options={
                'verbose_name': 'Learner',
                'verbose_name_plural': 'Learners',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(choices=[('term_1', 'Term 1'), ('term_2', 'Term 2'), ('term_3', 'Term 3')], max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_terms', to='tenant.school')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.academicyear')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.cohort')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.learningarea')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='tenant.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.term')),
            ],
            options={
                'verbose_name': 'Teacher assignment',
                'verbose_name_plural': 'Teacher assignments',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.academicyear')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.cohort')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tenant.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.term')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['tenant', 'is_active'], name='acad_year_active_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['tenant', 'start_date'], name='acad_year_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('tenant', 'label'), name='academics_year_tenant_label_unique'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant',), name='academics_one_active_year_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='academics_year_dates_ordered'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['tenant', 'is_active'], name='acad_cohort_active_idx'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['tenant', 'academic_year', 'grade_level'], name='acad_cohort_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('tenant', 'academic_year', 'grade_level', 'name'), name='academics_cohort_unique'),
        ),
        migrations.AddIndex(
            model_name='learningarea',
            index=models.Index(fields=['tenant', 'grade_level', 'is_active'], name='acad_learning_area_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningarea',
            constraint=models.UniqueConstraint(fields=('tenant', 'grade_level', 'code'), name='academics_learning_area_unique'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'is_active'], name='acad_learner_active_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'admission_number'], name='acad_learner_admission_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('tenant', 'admission_number'), name='academics_learner_admission_unique'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['tenant', 'is_active'], name='acad_term_active_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['academic_year', 'code'], name='acad_term_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('tenant', 'academic_year', 'code'), name='academics_term_year_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='academics_term_dates_ordered'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['tenant', 'teacher'], name='acad_assign_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['tenant', 'cohort'], name='acad_assign_cohort_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['tenant', 'learning_area'], name='acad_assign_learning_area_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'teacher', 'cohort', 'learning_area', 'academic_year', 'term'), name='academics_active_teacher_assignment_unique'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['tenant', 'student'], name='acad_enroll_student_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['tenant', 'cohort'], name='acad_enroll_cohort_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'student', 'cohort', 'academic_year', 'term'), name='academics_active_enrollment_unique'),
        ),
    ]
